name: 'fec_campaign_finance_pipeline'
version: '1.0.0'
config-version: 2

profile: 'fec_campaign_finance_pipeline'

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  fec_campaign_finance_pipeline:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
