name: 'nba_team_stats_pipeline'
version: '1.0.0'
config-version: 2

profile: 'nba_team_stats_pipeline'

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  nba_team_stats_pipeline:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
